### ISSUE TITLE
Slider dot size 

### ISSUE THREAD

**Issue by mathiask88** [godesign/nativeDroid2#12]
I think the slider dot is a little bit too small. I often need many trys to drag it.

**Comment by godesign** [comment]
I have increased the size of the dots from 16px to 20px. In my opinion its mostly an issue with touch sensitivity of jQueryMobile. I would say 20px is the limit which still looks nice :-)

Fixed in Commit:
https://github.com/godesign/nativeDroid2/commit/698f0006b6b07f568329dd61e6e467e24f8d045d

**Comment by mathiask88** [comment]
Much better now, thanks!
