### ISSUE TITLE
Flipswitch wave animation

### ISSUE THREAD

**Issue by mathiask88** [godesign/nativeDroid2#14]
If I press on the round button in a FlipSwitch the wave animation is triggered and the wave goes through the button which looks nice but on the left and right side the wave is bordered by the rectangle and not the rounded corners which looks not so nice ;) Is this possible to fix?

**Comment by godesign** [comment]
Unfortunately I cannot change the complete behavior because there will be an SVG-Element attached that ignores the overflow attributes.

But I will make some changes with the next update that the ripple there would be "light" so the user won't see it.

**Comment by godesign** [comment]
Just updated in commit https://github.com/godesign/nativeDroid2/commit/1576169fca8a15763e9c1e0c1813eed18fc1d89b#diff-cd44164adab6e7dd5df3c7823a7fb31fR78

**Comment by mathiask88** [comment]
Nice work!
