### ISSUE TITLE
Tab color

### ISSUE THREAD

**Issue by mathiask88** [godesign/nativeDroid2#16]
Tab background color should be the same color as the header. (https://www.google.com/design/spec/components/tabs.html#)

**Comment by godesign** [comment]
To be more precise, the tab background must be transparent and if its nested in the toolbar, it will adopt those background.

I've just written a small widget which let the tabs feels more native.
http://nd2.godesign.ch/examples/extended/tabs.html

Commit: https://github.com/godesign/nativeDroid2/commit/626eb380772ee0c9d792b22b5afd9f129a67a3b7
