### ISSUE TITLE
anchor click is showing blank page in single page application

### ISSUE THREAD

**Issue by allareddy** [godesign/nativeDroid2#19]
anchor click is showing blank page in single page application. when fixed with body { opacity: 0; } this one page is loading properly first time on second time visit panel is not opening.

**Comment by godesign** [comment]
Possible duplicate with https://github.com/godesign/nativeDroid2/issues/13 .

Otherwise can you please prepare an example (jsfiddle / codepen / ...) to reproduce that issue?
