### ISSUE TITLE
swipe issue in single page navigation

### ISSUE THREAD

**Issue by 2803media** [godesign/nativeDroid2#21]
Hi I notice that in single navigation (with anchor link) the swipe to open panel don't work?

I guess it come from this

     $(".ui-page:not('.nd2-no-menu-swipe')").on("swiperight swipeleft",function(e) {
		if($(".ui-page-active").jqmData("panel") !== "open") {
			if(e.type === "swiperight") {
				$(".ui-panel.ui-panel-position-left:first").panel("open");
			}
		}
    });

Do you know how to make the swipe working even in this kind of navigation?

Thanks

**Comment by godesign** [comment]
Can you make an example (jsfiddle / codepen /...) that I can reproduce your issue?

**Comment by godesign** [comment]
You can add class .nd2-no-menu-swipe to the data-role='page' tag and the navigation swipe will be disabled.

```
<div data-role="page" class="nd2-no-menu-swipe">
<!-- Page Content !-->
</div>
```

**Comment by 2803media** [comment]
Thanks for your feedback!
