### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mikelakat** [godesign/nativeDroid2#22]
Hello,

I have download the nativeDroid2 and is not working. the only thing when i try to run the index.html i get the following screen. Please can you help me to work it?
![help](https://cloud.githubusercontent.com/assets/6781485/8838426/31bde4ee-30d5-11e5-839b-8c82e2d07ff9.JPG)

**Comment by rvnerd** [comment]
Yeah, I noticed the same today. You only have to fix the paths for the CSS and JS files though.

              ../../css
              ../../jss

**Comment by mikelakat** [comment]
Thanks for the help.

now is working but when i click the blue cycle. maybe is this the issue now? "<nd2-include data-src"

<!DOCTYPE HTML>
<html>
	<head>
		<title>nativeDroid II - jQueryMobile Template</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" />
		<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css" />
		<link rel="stylesheet" href="vendor/waves/waves.min.css" />
		<link rel="stylesheet" href="vendor/wow/animate.css" />
		<link rel="stylesheet" href="css/nativedroid2.css" />
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
		<script src="vendor/waves/waves.min.js"></script>
		<script src="vendor/wow/wow.min.js"></script>
		<script src="js/nativedroid2.js"></script>
		<script src="nd2settings.js"></script>

		<meta name="mobile-web-app-capable" content="yes">
	 	<meta name="apple-mobile-web-app-capable" content="yes" />
  		<meta name="apple-mobile-web-app-status-bar-style" content="black" />

	</head>
	<body>

		<div data-role="page">

			<nd2-include data-src="examples/fragments/panel.left.html"></nd2-include>

			<div data-role="panel" id="bottomsheet" data-animate="false" data-position='bottom' data-display="overlay">
				<nd2-include data-src="examples/fragments/bottom.sheet.html"></nd2-include>
			</div>

			<div data-role="header" data-position="fixed" class="wow fadeInDown" data-wow-delay="0.2s">
				<a href="#bottomsheet" class="ui-btn ui-btn-right wow fadeIn" data-wow-delay='1.2s'><i class="zmdi zmdi-more-vert"></i></a>
				<a href="#leftpanel" class="ui-btn ui-btn-left wow fadeIn" data-wow-delay='0.8s'><i class="zmdi zmdi-menu"></i></a>
				<h1 class="wow fadeIn" data-wow-delay='0.4s'>Page Title</h1>
			</div>

			<div role="main" class="ui-content" data-inset="false">
				<p>(home)</p>
			</div>

		</div>

		

	</body>
</html>

**Comment by godesign** [comment]
Please make sure you're running it on a server environment (webserver / localhost) to make sure ajax calls will be executed.
