### ISSUE TITLE
Flash of unstyled content (FOUC)

### ISSUE THREAD

**Issue by webslash** [godesign/nativeDroid2#24]
There appears to be an issue with a flash of unstyled content.

See:
![fouc](https://cloud.githubusercontent.com/assets/1878691/8894086/493b343c-33aa-11e5-9b07-804428858f1a.png)

**Comment by scorpioeffect** [comment]
Ive been experiencing this as well. the un-styled content is there when the page is opened for about a second or so just before the glorious material design kicks in.

**Comment by godesign** [comment]
I tried to avoid that behavior by setting the opacity of the body to 0 while loading and when page ready to 1. But the FOUC still appears.

Any help or idea to this is very welcome.

**Comment by webslash** [comment]
Thanks @godesign for this fix!
Currently the fix will only work for non ajax loaded pages, you should add this to the pagecreate event to make sure ajax loaded pages are made visible as well:


    $(document).bind("pagecreate", function(e) {
       $('body').css('opacity','1!important');
    });
