### ISSUE TITLE
Native droid Grid System has problem in some mobiles

### ISSUE THREAD

**Issue by minamorsali** [godesign/nativeDroid2#26]
Hello ,
and thank you for this great and nice design for mobile programs. There are some problem with some mobiles with lower version , for example every footer menu item show in one line (not all in one line) , how can we fix this issue?

thank you

**Comment by godesign** [comment]
You could easily switch from flexboxgrid.min.css to bootstrap grid system (http://getbootstrap.com/customize/ - only activate the "Grid System"-Tick).

The CSS-Syntax is pretty much the same and as soon as you switched over you would have the grid aligned.
