### ISSUE TITLE
Expandable Search

### ISSUE THREAD

**Issue by webslash** [godesign/nativeDroid2#30]
Hi godesign.

Would love to see the Expendable Search material design pattern to be included.

![image](https://cloud.githubusercontent.com/assets/1878691/9289394/42d9d46c-436e-11e5-8cb7-94183bf5f041.png)
![image](https://cloud.githubusercontent.com/assets/1878691/9289396/46e58790-436e-11e5-969d-0da5aaf4e381.png)

Touching the search icon causes the toolbar to transform, clearing other content and displaying a search text field.

Read more: https://www.google.com/design/spec/patterns/search.html#search-in-app-search

Thanks for all your hard work, nativeDroid2 is the best!

**Comment by godesign** [comment]
The first version of a search-bar is available now:
http://nd2.godesign.ch/examples/extended/search.html

Autocomplete depends on:
http://jqueryui.com/autocomplete/

**Comment by webslash** [comment]
Awesome @godesign!

How would you go about implementing this without the auto-complete? 
(I'm working with an external search API and can't control it's return values.)

In my case I would need the search bar function but when someone enters text, it should not auto-complete. I just want them to submit the search "form" (so I can get the value) and display the results.

Could you provide a non auto-complete example?

Thanks
