### ISSUE TITLE
Can't run a demo

### ISSUE THREAD

**Issue by gozzilli** [godesign/nativeDroid2#31]
I've cloned the master and tried to run the demo. Both

     python -m SimpleHTTPServer

and 

    http-server --cors

from node.js fail to run the demo, and I only get:

![screenshot 2015-08-18 18 36 15](https://cloud.githubusercontent.com/assets/1502267/9337579/0f7206be-45d8-11e5-8259-af10f7259380.png)

The errors I get, from the server:

    "POST /examples/fragments/bottom.sheet.html" Error (404): "Not found"
    "POST /examples/fragments/bottom.sheet.html" Error (404): "Not found"

and from the client:

    POST http://localhost:8080/examples/fragments/panel.left.html 405 (Method Not Allowed)
    POST http://localhost:8080/examples/fragments/bottom.sheet.html 405 (Method Not Allowed)

What am I doing wrong? Thanks!

**Comment by godesign** [comment]
It looks like a problem with CORS while those two files are included by jquery.load-method.

May this answer on stackoverflow will help you any further: http://stackoverflow.com/questions/20698723/cors-405-method-not-allowed

**Comment by matejuh** [comment]
nd2-include uses POST for loading html. This is HTTP non-standard behaviour and you have to customize server to load static resources with POST request. I suggest to change nd2-include module to use GET instead of POST.

**Comment by godesign** [comment]
@matejuh thanks for your input. I just changed the loading behaviour

**Comment by matejuh** [comment]
Great, thanks! I think it will be much better for many people. I'm not Javascript developer and it took me long time to realize that when I remove post params then GET is called and wasn't sure if I should send merge request...

**Comment by violinazh** [comment]
Hello guys,
I'm quite new to web programming and I am developing a simple web app. I would like to use the nativeDroid2 features and I cloned the repository but I'm unable to load the demo on my web browser. What I am trying to do is to run the index.html in the root directory but I only get a plain page with a title and some text as seen below. I also read the article about nd2-include but I couldn't understand much of it, unfortunately.
![screenshot from 2018-03-15 18-09-14](https://user-images.githubusercontent.com/15687836/37479137-34d7a20e-287c-11e8-9dc2-c61a618de5f8.png)

**Comment by pazDontExist** [comment]
This happen because you are trying to open it in browser as file. Chrome block this kind of stuff cause is trying to gain access to a file in your computer…

Translation: put the file under a web server (like XAMPP) and open it with a correct url ( http://localhost/MyAwesomeProject <http://localhost/MyAwesomeProject>)
