### ISSUE TITLE
dont find the doc

### ISSUE THREAD

**Issue by jrm0695** [godesign/nativeDroid2#33]
please is anybody able to give me the doc? the project looks awesome but there are many files in the zip I dont know the ones to include in my phonegap project in order to get started. 
thank you

**Comment by exos** [comment]
Check this: http://nd2.godesign.ch/examples/elements/text.html

**Comment by jrm0695** [comment]
thank you very much. it seems real-world exemples aren't available yet aren't they ?

**Comment by jrm0695** [comment]
I have just a few more questions : 
1. What is the purpose of "wave", "wow", and chartist ?
2. Do I have to include flexboxgird.css and material-design-iconic-font.css ? 
3. Where can I find a darker version of nativeAndroid ?

**Comment by exos** [comment]
> 1. What is the purpose of "wave" and "wow"

Wave add an effect when a button is touched

> 3. Where can I find a darker version of nativeAndroid ? 

Check: https://github.com/godesign/nativeDroid2/issues/15
