### ISSUE TITLE
Problem with blank pages

### ISSUE THREAD

**Issue by andrea75** [godesign/nativeDroid2#34]
After the "body { opacity: 0; }" tag style implementation, that solved the FOUC problem, now I have a new one. With some browsers (ex. Samsung stock browser) when I click on back buttons (on the app, or on the phisical phone button) the back page loaded appear blank.
If I remove body { opacity: 0; } I have again the FOUC problem. There is a solution for this?

Sorry for my english.

**Comment by webslash** [comment]
Hi @andrea75 

Are you still having this issue on the latest version?
I had the same problem before but wrote a fix which is now implemented, see:
https://github.com/godesign/nativeDroid2/issues/24

**Comment by andrea75** [comment]
Yes @webslash , it happen with the latest version. As I said the fix #24 solve the FOUC problem, but with this fix now I have a blank screen when I back pages.

**Comment by godesign** [comment]
@andrea75 You can try updating the method ```iniSmoothTransition``` (https://github.com/godesign/nativeDroid2/blob/master/js/nativedroid2.js#L661-L669) with the following lines:

```
_self.iniSmoothTransition = function() {
		$("body").addClass("nd2-ready");
		$(document).on("pagechange",function(){
			$("body").removeClass("nd2-ready");
		})
		.bind("pagecontainershow ", function(e) {
		   $('body').css('opacity','1');
		});
		$(window).on('navigate',function(event,state) {
			$('body').css('opacity','1');
		});
};
```

I will make an update of the resources if you can confirm that this works.

**Comment by andrea75** [comment]
@godesign it seems to be works! Thanks!
