### ISSUE TITLE
safari button animations

### ISSUE THREAD

**Issue by chrishofer** [godesign/nativeDroid2#35]
In safari (v. 8.0.8) and mobile safari (ios 8.4) the touch animations in round buttons are drawn over the whole rectangular area surrounding the button.

**Comment by patrickjauernig** [comment]
This bug is also present in Chrome v45 (and therefore in the current Android WebView?) and in Firefox v40.

**Comment by patrickjauernig** [comment]
Solved the problem by making the fab border radius important:

**Comment by godesign** [comment]
@patrickjauernig thanks for your help. I just fixed it.
