### ISSUE TITLE
nd2 search with filterable support

### ISSUE THREAD

**Issue by valinaga** [godesign/nativeDroid2#37]
Hi,

It would be great to add filterable support to the header search.
I tried myself, but for some reasons it's not working, although I properly referenced it in data-input attribute of the listview.

**Comment by godesign** [comment]
The Search on top is not linked to an autocomplete-filterable-list on the page.

To have the ability performing a global search.

The example code:

``new $.nd2Search({
  placeholder : "Input Placeholder",   // Placeholder in the search field
  defaultIcon : "globe-alt",  // optional: icon | null
  source : [{ label : 'Displayed Value', value : 'real-value', icon : 'custom-icon'}],   // autocomplete : option-source
  fn : function(result) { // this function will be executed when a valid result item is selected
    console.log('--- Your custom handling ---');
    console.log('you picked: ');
    console.log(result);
  }
});``

It uses the Autocomplete from jQueryUI (http://api.jqueryui.com/autocomplete/) not the one from jQuery-Mobile (http://demos.jquerymobile.com/1.4.0/listview-autocomplete/).
