### ISSUE TITLE
Left Panel does not open after doing back in Cordova

### ISSUE THREAD

**Issue by genriq** [godesign/nativeDroid2#41]
Hi, 

First of all, thank you for developing this **wonderful template**.

I am using nativeDroid2 with Cordova. From my APP I open the left panel on the main page and from there navigate to another page where I also open the left panel. When I go back to the main page, the panel does not open anymore. (If I do the same but without opening the left panel on the second page, the left panel from the main page still works when I return). This same effect appears with the bottom sheets. I tried many things but cannot figure out how to fix it, 

**If anyone can help me with at least some ideas I would really appreciate it.**

Thanks!

**Comment by pazDontExist** [comment]
Hi genriq, can you give us the code you wrote ?
im using this amaizng template too in a cordova project and im not facing this problem. But...for experience is surely some javascript lib/script that is givin problem...

like...
if you are using multipages and your "back" is an "<a>" try to use "<a href="link.html" rel="external" ..."

it will make everything work (this cause some jquerymobile stuff)

**Comment by genriq** [comment]
Thanks for the answer. I finally found the problem: I used the same ID names for the paanels in different pages, i.e: id="leftpanel" and that seems to break everything. Lesson learned, each panel / sheet on each page should have an individual ID name. ie: id="leftpanel_main", id="leftpanel_items", id="leftpanel_buy".. .etc, same applies to the bottom sheets.

Cheers.
