### ISSUE TITLE
panel left, bottom sheet question & button

### ISSUE THREAD

**Issue by danilarsen** [godesign/nativeDroid2#43]
Can you give me one example of:

a dialog popup from panel left or bottom sheet ?

and what is the action of a button to link to other html file?

thanks!

**Comment by pazDontExist** [comment]
is very easy. in your page inside the tag 
```html
<div data-role="page">
```

just put this.

```html
<div data-role="popup" id="mypopup">
    <div data-role="header">
        <h1 class='nd-title'>HIIII IM THE MODAL TITLE !!!!</h1>
    </div>
     <div data-role="content">
         <p>Hi ! Im the modal Content!</p>
        <a href="mypage.html" data-rel="back" data-role="button" data-inline="true" class="ui-btn ui-btn-primary"><i class='zmdi zmdi-check'></i> Soooo GOOD !</a>
        <a href="mypage" data-rel="back" data-role="button" data-inline="true" class="ui-btn ui-btn-primary"><i class='zmdi zmdi-cancel'></i> Cancel</a>
    </div>
</div>
```

after for make it be called just create a link in this way

```html
<a href="#mypopup" data-rel="popup" data-position-to="window" data-role="button" data-inline="true" data-transition="pop"><i class='lIcon fa fa-external-link'></i> MyPopUP</a>
```

ofc...if you are using the basic template the page where to add/modify the link is in 
**pages/fragments/panel.left.html**

**Comment by danilarsen** [comment]
thanks! glad the help!!, what about a select option in the panel left it doesn't show me the options....

**Comment by pazDontExist** [comment]
you mean the dropdown list ?

2015-10-27 17:12 GMT+01:00 danilarsen <notifications@github.com>:

> thanks! glad the help!!, what about a select option in the panel left it
> doesn't show me the options....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/godesign/nativeDroid2/issues/43#issuecomment-151554323>
> .
>



-- 

*"Il Parlamento è un simbolo, come lo è l'atto di distruggerlo... sono gli
uomini che conferiscono potere ai simboli... da solo un simbolo è privo di
significato ma con un bel numero di persone alle spalle far saltare un
palazzo può cambiare il mondo"*

**Comment by danilarsen** [comment]
Forms
Select
Select (single)

<label for="select-choice-1b" class="select">Select</label>
<select name="select-choice-1" id="select-choice-1b" data-native-menu="false">
    <option value="javascript">JavaScript</option>
    <option value="css">CSS</option>
    <option value="html">HTML</option>
    <option value="csharp">C#</option>
    <option value="java">Java</option>
</select>

this select in the panel left

**Comment by pazDontExist** [comment]
Honestly I prefer the Silvio Moreto select box  heck it out here
https://silviomoreto.github.io/bootstrap-select/

Is very easy to use and to integrate here
But anyway, like every other thing html tag here, just follow up the
example pages and normal markup with nativedroid  styles class
Il 27/Ott/2015 19:25, "danilarsen" <notifications@github.com> ha scritto:

**Comment by danilarsen** [comment]
ok, but my point is, in the panel left if you put a select box you didn't see the options 'cause the options are showed in the index.html not in the panel.left.html...

**Comment by pazDontExist** [comment]
Dude.  Can you post the code ? My crystal ball tell me you are doing
something wrong
Il 28/Ott/2015 02:41, "danilarsen" <notifications@github.com> ha scritto:

**Comment by danilarsen** [comment]
<div data-role="panel" id="leftpanel" data-display="overlay" data-position-fixed="true" >
		<div class='nd2-sidepanel-profile wow fadeInDown'>
                      <img class='profile-background' src="http://lorempixel.com/400/200/abstract/2/" />
					<div class="row">
						<div class='col-xs-8'>
							<div class='box profile-text'>
								<strong>Some User</strong>
							</div>
						</div>
					</div>
				</div>
				<hr class="inset">
				<form>
			   <div class="ui-content wow fadeIn" data-inset="false" data-wow-delay="0.2s">
						<div class="box">		
							<label for="select-choice-1b" class="select">Language</label>
				<select name="select-choice-1" id="select-choice-1b" data-native-menu="false">
									<option value="javascript">JAVASCRIPT</option>
											<option value="css">CSS</option>
										</select>		
				
				       </div>
				    </div>   
				</form>		
				</div>
			</div>

**Comment by pazDontExist** [comment]
ok, now i got it...

just write your select in this way

```html
<select name="select" id="select">
    <option value="javascript">JAVASCRIPT</option>
    <option value="css">CSS</option>
</select>    
```

the problem is: that  id is binded to jquery function...for this it open the content in another part

**Comment by danilarsen** [comment]
ok, but is not the same "effect",but if this is the solution, fine by me. thanks!

**Comment by pazDontExist** [comment]
actually for hereditate the same effect i have some script in mind...i'll
let you know when i'll have time....sorry...have to go back working

2015-10-29 18:26 GMT+01:00 danilarsen <notifications@github.com>:

> ok, but is not the same "effect",but if this is the solution, fine by me.
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/godesign/nativeDroid2/issues/43#issuecomment-152257003>
> .
>



-- 

*"Il Parlamento è un simbolo, come lo è l'atto di distruggerlo... sono gli
uomini che conferiscono potere ai simboli... da solo un simbolo è privo di
significato ma con un bel numero di persone alle spalle far saltare un
palazzo può cambiare il mondo"*

**Comment by danilarsen** [comment]
thanks!, pls let me know!.
