### ISSUE TITLE
Chat Style

### ISSUE THREAD

**Issue by pazDontExist** [godesign/nativeDroid2#45]
Hiii !!!
Thanks for your amazing work...

well...actually im goin crazy cause i'm tring to make a page in chat style and my only problem actually is just one and i'm hitting my head over the table last 5 hours...i feel stupid.... 

The only thing i need is to understand how to make the msgbox (where user write his msg) be the 80% of the page width and the 20% being occupied by the button for send the message.

Ofc,...when i end i send here the code so, if you want @godesign , you can implement in next release or in the demo

**Comment by pazDontExist** [comment]
nevermind ! Solved by myself...coffe and hit head worked!

```html
<div data-role="footer" data-position="fixed">
    <div class="row center-xs">
        <div class="col-xs-10">
            <div class="box">
                <textarea cols="40" rows="8" name="msgbox" id="msgbox" maxlength="250" placeholder="Scrivi qui il tuo messaggio"></textarea>
            </div>
         </div>
	<div class="col-xs-2">
	     <div class="box">
                 <a href="#" onclick="sendMsg();" class="ui-btn ui-btn-inline ui-btn-fab"><i class='zmdi zmdi-comment zmd-3x'></i></a>
             </div>
          </div>
     </div>
</div>
```

**Comment by godesign** [comment]
@pazDontExist thanks for the input. I'll check what I can do :+1:  Such things are always welcome.
