### ISSUE TITLE
leftpanel

### ISSUE THREAD

**Issue by viraj310** [godesign/nativeDroid2#46]
![untitled](https://cloud.githubusercontent.com/assets/15348278/10825803/a28e46c8-7e8c-11e5-898b-0931f1be6ad0.png)

<b>Error in loading leftpanel...

**Comment by viraj310** [comment]
<!DOCTYPE HTML>
<html>
	<head>
		<title>nativeDroid II - jQueryMobile Template</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" />
		<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css" />
		<link rel="stylesheet" href="vendor/waves/waves.min.css" />
		<link rel="stylesheet" href="vendor/wow/animate.css" />
		<link rel="stylesheet" href="css/nativedroid2.css" />

		<meta name="mobile-web-app-capable" content="yes">
	 	<meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

	</head>
	<body>

		<div data-role="page">

			<nd2-include data-src="examples/fragments/panel.left.html"></nd2-include>

			<div data-role="panel" id="bottomsheet" data-animate="false" data-position='bottom' data-display="overlay">
				<nd2-include data-src="examples/fragments/bottom.sheet.html"></nd2-include>
			</div>

			<div data-role="header" data-position="fixed" class="wow fadeInDown" data-wow-delay="0.2s">
				<a href="#bottomsheet" class="ui-btn ui-btn-right wow fadeIn" data-wow-delay='1.2s'><i class="zmdi zmdi-more-vert"></i></a>
				<a href="#leftpanel" class="ui-btn ui-btn-left wow fadeIn" data-wow-delay='0.8s'><i class="zmdi zmdi-menu"></i></a>
				<h1 class="wow fadeIn" data-wow-delay='0.4s'>Page Title</h1>
			</div>

			<div role="main" class="ui-content" data-inset="false">
				<p>(home)</p>
			</div>

		</div>

		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
		<script src="//ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
		<script src="vendor/waves/waves.min.js"></script>
		<script src="vendor/wow/wow.min.js"></script>
		<script src="js/nativedroid2.js"></script>
		<script src="nd2settings.js"></script>

	</body>
</html>

**Comment by pazDontExist** [comment]
try to put http: before the //
on everywhere
and be sure that you have on whitelist all the websites (just adding * on
the whitelist) and let me know


2015-10-29 20:13 GMT+01:00 viraj310 <notifications@github.com>:

> <!DOCTYPE HTML>
>
>
> nativeDroid II - jQueryMobile Template
>
>     <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" />
>     <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css" />
>     <link rel="stylesheet" href="vendor/waves/waves.min.css" />
>     <link rel="stylesheet" href="vendor/wow/animate.css" />
>     <link rel="stylesheet" href="css/nativedroid2.css" />
>
>     <meta name="mobile-web-app-capable" content="yes">
>     <meta name="apple-mobile-web-app-capable" content="yes" />
> <meta name="apple-mobile-web-app-status-bar-style" content="black" />
>
> </head>
> <body>
>
>     <div data-role="page">
>
>         <nd2-include data-src="examples/fragments/panel.left.html"></nd2-include>
>
>         <div data-role="panel" id="bottomsheet" data-animate="false" data-position='bottom' data-display="overlay">
>             <nd2-include data-src="examples/fragments/bottom.sheet.html"></nd2-include>
>         </div>
>
>         <div data-role="header" data-position="fixed" class="wow fadeInDown" data-wow-delay="0.2s">
>             <a href="#bottomsheet" class="ui-btn ui-btn-right wow fadeIn" data-wow-delay='1.2s'><i class="zmdi zmdi-more-vert"></i></a>
>             <a href="#leftpanel" class="ui-btn ui-btn-left wow fadeIn" data-wow-delay='0.8s'><i class="zmdi zmdi-menu"></i></a>
>             <h1 class="wow fadeIn" data-wow-delay='0.4s'>Page Title</h1>
>         </div>
>
>         <div role="main" class="ui-content" data-inset="false">
>             <p>(home)</p>
>         </div>
>
>     </div>
>
>     <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
>     <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
>     <script src="//ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
>     <script src="vendor/waves/waves.min.js"></script>
>     <script src="vendor/wow/wow.min.js"></script>
>     <script src="js/nativedroid2.js"></script>
>     <script src="nd2settings.js"></script>
>
> </body>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/godesign/nativeDroid2/issues/46#issuecomment-152291221>
> .
>



-- 

*"Il Parlamento è un simbolo, come lo è l'atto di distruggerlo... sono gli
uomini che conferiscono potere ai simboli... da solo un simbolo è privo di
significato ma con un bel numero di persone alle spalle far saltare un
palazzo può cambiare il mondo"*

**Comment by viraj310** [comment]
<!DOCTYPE HTML>
<html>
	<head>
		<title>nativeDroid II - jQueryMobile Template</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" />
		<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css" />
		<link rel="stylesheet" href="vendor/waves/waves.min.css" />
		<link rel="stylesheet" href="vendor/wow/animate.css" />
		<link rel="stylesheet" href="css/nativedroid2.css" />

		<meta name="mobile-web-app-capable" content="yes">
	 	<meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

	</head>
	<body>

		<div data-role="page">

			<nd2-include data-src="examples/fragments/panel.left.html"></nd2-include>

			<div data-role="panel" id="bottomsheet" data-animate="false" data-position='bottom' data-display="overlay">
				<nd2-include data-src="examples/fragments/bottom.sheet.html"></nd2-include>
			</div>

			<div data-role="header" data-position="fixed" class="wow fadeInDown" data-wow-delay="0.2s">
				<a href="#bottomsheet" class="ui-btn ui-btn-right wow fadeIn" data-wow-delay='1.2s'><i class="zmdi zmdi-more-vert"></i></a>
				<a href="#leftpanel" class="ui-btn ui-btn-left wow fadeIn" data-wow-delay='0.8s'><i class="zmdi zmdi-menu"></i></a>
				<h1 class="wow fadeIn" data-wow-delay='0.4s'>Page Title</h1>
			</div>

			<div role="main" class="ui-content" data-inset="false">
				<p>(home)</p>
			</div>

		</div>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
		<script src="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
		<script src="vendor/waves/waves.min.js"></script>
		<script src="vendor/wow/wow.min.js"></script>
		<script src="js/nativedroid2.js"></script>
		<script src="nd2settings.js"></script>

	</body>
</html>


<b> Not Working

**Comment by pazDontExist** [comment]
ok, check my screenshot...and check the paths if are like mine (ive just downloaded right now nativedroid and setup new project and made my mod...)
![shot](https://cloud.githubusercontent.com/assets/15037424/10832049/48ca5148-7e89-11e5-9faf-2db2ae463889.jpg)

**Comment by viraj310** [comment]
![capture](https://cloud.githubusercontent.com/assets/15348278/10854231/67f38274-7f60-11e5-844d-32790c71e645.JPG)

**Comment by viraj310** [comment]
<h2>keeping both files (index and panel.left.html) are in the same level directory loads sidebar.... But

![1](https://cloud.githubusercontent.com/assets/15348278/10855910/4435a8f8-7f6a-11e5-98f2-e52051d51e1e.JPG)

<h2>after clinking any link.... like text elements,,,, it show following error
![2](https://cloud.githubusercontent.com/assets/15348278/10855919/4c021bac-7f6a-11e5-9d74-e64f1dce0454.JPG)

**Comment by viraj310** [comment]
????

**Comment by godesign** [comment]
@viraj310 This 503 "Service unavailable" is an error that occurs not due to the nativeDroid2, you will find some help in SO upon this (For Example: http://stackoverflow.com/questions/25644487/httpd-returning-503-service-unavailable-with-mod-proxy-for-tomcat-8)

@pazDontExist Many thanks for your detailed explanations :+1:
