### ISSUE TITLE
Extended Elements: Bottom sheet

### ISSUE THREAD

**Issue by godesign** [godesign/nativeDroid2#5]
Make some more examples of bottom sheets.

https://www.google.com/design/spec/components/bottom-sheets.html

**Comment by JonasHaouzi** [comment]
Hi GoDesign.

I'm looking for dev. who are open to create a custom jQuery mobile for a live results project.

What you do is REALLY close to what we need and I was wondering if you would be interested working with us for this mission.

Please contact me if you want to open the discussions.

Many thanks.

Jonas

**Comment by godesign** [comment]
Examples added and functionality expanded https://github.com/godesign/nativeDroid2/commit/6658b61b953feef797147c3532a576ea6a6ec534
