### ISSUE TITLE
Can't install & run it properly

### ISSUE THREAD

**Issue by sunan26** [godesign/nativeDroid2#6]
Hi godesign,

I'm try to download the code and try to run it locally, but I can't see the application working properly as example in website.

please find the screen capture:
<img width="583" alt="capture" src="https://cloud.githubusercontent.com/assets/13212758/8538697/cce47628-24b3-11e5-9219-557784c7b21f.PNG">

and when I'm try to click on the left panel, nothing is happen

can you help me to sort it out ?

Thank you,
regards,
sunan26

**Comment by g6307352** [comment]
You can use relative path like this.
Before : <link rel="stylesheet" href="/css/nativedroid2.css" />
After : <link rel="stylesheet" href="css/nativedroid2.css" />

**Comment by godesign** [comment]
As g6307352 described, adjust the paths for css and js resources as your project need.

**Comment by sunan26** [comment]
thank you g6307352 for your explanation

**Comment by viraj310** [comment]
not working
