### ISSUE TITLE
nativeDroid2 panel bug with long page

### ISSUE THREAD

**Issue by g6307352** [godesign/nativeDroid2#7]
1. Scrolling to Top when Panel Opens.
![1](https://cloud.githubusercontent.com/assets/13162960/8542518/466c5cbe-24d1-11e5-9793-f071cde65c82.png)
![2](https://cloud.githubusercontent.com/assets/13162960/8542519/466dda6c-24d1-11e5-8747-03664f75c05f.png)

2. Scrolling when panel is open.
![3](https://cloud.githubusercontent.com/assets/13162960/8542523/4c7feb8e-24d1-11e5-9f13-599d15816d03.png)
![4](https://cloud.githubusercontent.com/assets/13162960/8542524/4ca6283a-24d1-11e5-9cf7-59098ad9911c.png)

**Comment by godesign** [comment]
It seems that this is a general jQM-Issue. I'll fix it according to this solution:
http://stackoverflow.com/questions/22672236/jquery-mobile-panel-open-scrolls-page-to-the-top-how-to-change-this

**Comment by godesign** [comment]
Fixed:
https://github.com/godesign/nativeDroid2/commit/dfba674fea493c783a7120f57b3015bcba9c9ad4
