### ISSUE TITLE
Do not work multi-select of forms in the pc

### ISSUE THREAD

**Issue by g6307352** [godesign/nativeDroid2#8]
Default:
![1](https://cloud.githubusercontent.com/assets/13162960/8542624/f5a92d1a-24d1-11e5-8e41-00f22775b36b.png)

Click:
![2](https://cloud.githubusercontent.com/assets/13162960/8542626/f5d37638-24d1-11e5-954e-12be68642e40.png)

**Comment by godesign** [comment]
I will do some adjustments and create further examples.

(https://api.jquerymobile.com/selectmenu/)

**Comment by godesign** [comment]
Fixed:
https://github.com/godesign/nativeDroid2/commit/dfba674fea493c783a7120f57b3015bcba9c9ad4
