### ISSUE TITLE
Fabs support

### ISSUE THREAD

**Issue by g6307352** [godesign/nativeDroid2#9]
http://nd2.godesign.ch/examples/elements/buttons.html
Fabs are not support?

**Comment by godesign** [comment]
This is how you can create a FAB-Button:


```html
<a href="#" class="ui-btn ui-btn-inline ui-btn-fab ui-btn-raised clr-primary
waves-effect waves-button waves-effect waves-button">
     <i class="zmdi zmdi-mic-off zmd-2x"></i>
</a>
```


Or do you think about the FAB-Positioning?

**Comment by g6307352** [comment]
Yes, I want to FAB-Positioning.
Like right and bottom.

**Comment by godesign** [comment]
I've closed this and created a new ticket with this "enhancement-request"
https://github.com/godesign/nativeDroid2/issues/10
